# Generated by Django 5.2.4 on 2025-08-01 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_usuario_seguidos_publication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="user",
            new_name="autor",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="content",
            new_name="contenido",
        ),
        migrations.RenameField(
            model_name="publication",
            old_name="created_at",
            new_name="creado",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="image",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="seguidos",
        ),
        migrations.AddField(
            model_name="publication",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True, related_name="dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="publicaciones/"),
        ),
        migrations.AddField(
            model_name="publication",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="publicaciones/"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="ciudad_residencia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="seguidores",
            field=models.ManyToManyField(
                blank=True, related_name="siguiendo", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
