# Generated by Django 5.2.4 on 2025-08-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_user_publication_autor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(
                default="perfiles/default_doctor.png", upload_to="perfil/"
            ),
        ),
    ]
