# Generated by Django 5.2.4 on 2026-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
