# Generated by Django 5.2.4 on 2026-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
