# Generated by Django 5.2.4 on 2026-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='titulo_profesional',
            field=models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Dra.', 'Dra.')], max_length=10, null=True),
        ),
    ]
