# Generated by Django 5.2.4 on 2026-02-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_usuario_titulo_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['creado']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['publicacion', 'creado'], name='core_coment_publica_563682_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-creado', 'autor'], name='core_public_creado_dee1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['es_profesional', 'especialidad'], name='core_usuari_es_prof_cb18b8_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['matricula'], name='core_usuari_matricu_577dae_idx'),
        ),
    ]
