# Generated by Django 5.2.4 on 2026-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bloodtestpayment_userwidgetpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwidgetpreference',
            name='rojito_window_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userwidgetpreference',
            name='rojito_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
